import React, { useState } from 'react';
import { ArrowRight, Check, Clock3, FlaskConical, Pill, Search, ShoppingBag, ShieldCheck, TestTube2 } from 'lucide-react';
import { useApp } from '../context/AppContext';

type Kind = 'pharmacy' | 'diagnostics' | 'laboratory';
const data = {
  pharmacy: { icon: Pill, eyebrow: ['Verified medicines, delivered with care', 'प्रमाणित दवाएं, भरोसे के साथ'], title: ['Your pharmacy, made personal.', 'आपकी फार्मेसी, अब और आसान।'], desc: ['Prescription fulfilment, wellness essentials and pharmacist guidance in one trusted place.', 'प्रिस्क्रिप्शन दवाएं, हेल्थ प्रोडक्ट्स और फार्मासिस्ट की सलाह — एक भरोसेमंद जगह पर।'], action: ['Explore pharmacy', 'फार्मेसी देखें'], items: [['Diabetes Care Pack','₹649','30-day essentials'],['BP Monitor','₹1,299','Home monitoring'],['Vitamin D3','₹249','30 softgels']] },
  diagnostics: { icon: TestTube2, eyebrow: ['Accurate answers. Thoughtful care.', 'सटीक जांच, बेहतर देखभाल।'], title: ['Tests that fit around your life.', 'आपकी सुविधा के अनुसार जांच।'], desc: ['Book certified diagnostic tests with transparent pricing and home sample collection.', 'पारदर्शी कीमतों और होम सैंपल कलेक्शन के साथ प्रमाणित टेस्ट बुक करें।'], action: ['Book diagnostic test', 'डायग्नोस्टिक टेस्ट बुक करें'], items: [['Complete Blood Count','₹299','Report in 8 hours'],['Thyroid Profile','₹549','T3, T4 & TSH'],['HbA1c','₹399','Diabetes monitoring']] },
  laboratory: { icon: FlaskConical, eyebrow: ['Reliable reports for confident decisions', 'विश्वसनीय रिपोर्ट, सही निर्णय।'], title: ['A lab experience built on trust.', 'विश्वास पर आधारित लैब अनुभव।'], desc: ['Quality-controlled pathology and preventive screening with digital reports.', 'क्वालिटी-कंट्रोल्ड पैथोलॉजी और डिजिटल रिपोर्ट के साथ प्रिवेंटिव स्क्रीनिंग।'], action: ['View lab tests', 'लैब टेस्ट देखें'], items: [['Full Body Health Check','₹1,499','72 parameters'],['Liver Function Test','₹699','11 markers'],['Vitamin Profile','₹1,199','B12 & D']] }
} as const;

export const ServiceCatalog: React.FC<{kind: Kind}> = ({ kind }) => {
  const { language, openAuthModal } = useApp(); const [selected, setSelected] = useState<string | null>(null); const d = data[kind], Icon = d.icon, hi = language === 'hi';
  return <div className="min-h-[70vh] bg-slate-50">
    <section className="overflow-hidden bg-[#0b2545] py-14 text-white"><div className="mx-auto grid max-w-7xl items-center gap-8 px-4 sm:px-6 lg:grid-cols-[1fr_.7fr]"><div><span className="inline-flex items-center gap-2 rounded-full border border-emerald-400/25 bg-emerald-400/10 px-3 py-1 text-xs font-bold text-emerald-200"><ShieldCheck className="h-3.5 w-3.5" />{d.eyebrow[hi ? 1 : 0]}</span><h1 className="mt-5 max-w-2xl text-4xl font-black tracking-tight sm:text-5xl">{d.title[hi ? 1 : 0]}</h1><p className="mt-4 max-w-xl text-sm leading-6 text-slate-300">{d.desc[hi ? 1 : 0]}</p><button onClick={openAuthModal} className="mt-7 rounded-xl bg-emerald-400 px-5 py-3 text-sm font-black text-[#0b2545] shadow-lg">{d.action[hi ? 1 : 0]} <ArrowRight className="ml-1 inline h-4 w-4" /></button></div><div className="relative mx-auto grid h-52 w-52 place-items-center rounded-full border-[18px] border-white/10 bg-gradient-to-br from-[#0f4c81] to-emerald-600 shadow-2xl"><Icon className="h-20 w-20 text-white" /><span className="absolute -bottom-3 rounded-xl bg-white px-3 py-2 text-xs font-black text-[#0b2545] shadow-lg">Trusted care</span></div></div></section>
    <section className="mx-auto max-w-7xl px-4 py-12 sm:px-6"><div className="mb-7 flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-xs font-black uppercase tracking-[.18em] text-emerald-700">{hi ? 'लोकप्रिय विकल्प' : 'Popular options'}</p><h2 className="mt-1 text-2xl font-black text-slate-900">{hi ? 'स्पष्ट कीमत। सरल बुकिंग।' : 'Clear pricing. Simple booking.'}</h2></div><div className="flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs text-slate-400"><Search className="h-4 w-4" />{hi ? 'सेवा या टेस्ट खोजें' : 'Search a service or test'}</div></div><div className="grid gap-5 md:grid-cols-3">{d.items.map(([name,price,detail]) => <article key={name} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-50 text-emerald-700"><Icon className="h-5 w-5" /></div><h3 className="mt-5 font-black text-slate-900">{name}</h3><p className="mt-1 text-xs text-slate-500">{detail}</p><div className="mt-5 flex items-center justify-between"><strong className="text-lg text-[#0f4c81]">{price}</strong><button onClick={() => setSelected(name)} className="rounded-xl bg-slate-900 px-3 py-2 text-xs font-bold text-white">{hi ? 'चुनें' : 'Select'}</button></div></article>)}</div><div className="mt-10 grid gap-4 rounded-3xl border border-emerald-100 bg-emerald-50/60 p-6 md:grid-cols-3">{[[Clock3,hi?'लचीले स्लॉट':'Flexible slots'],[Check,hi?'डिजिटल रिपोर्ट':'Digital reports'],[ShoppingBag,hi?'सुरक्षित भुगतान':'Secure payments']].map(([I,label]) => {const C=I as React.ElementType; return <div key={label as string} className="flex items-center gap-3 text-sm font-bold text-slate-700"><C className="h-5 w-5 text-emerald-700" />{label}</div>})}</div></section>
    {selected && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4"><div className="w-full max-w-md rounded-3xl bg-white p-6 text-center shadow-2xl"><Check className="mx-auto h-10 w-10 text-emerald-600" /><h3 className="mt-3 text-xl font-black">{selected}</h3><p className="mt-2 text-sm text-slate-500">{hi ? 'आपकी रिक्वेस्ट सेव हो गई है। हमारी टीम जल्द संपर्क करेगी।' : 'Your request is saved. Our care team will contact you shortly.'}</p><button onClick={() => setSelected(null)} className="mt-5 rounded-xl bg-[#0f4c81] px-5 py-2.5 text-sm font-bold text-white">{hi?'हो गया':'Done'}</button></div></div>}
  </div>;
};
